# /etc/liveusb/profiles/g/make.conf
# Deployed into chroot by v script (0etap / chroot_script).
# Edit here, not in the heredoc.

#ABI_X86="64 32" 
L10N="pl"
ACCEPT_LICENSE="*"
RUBY_TARGETS="ruby32"
GRUB_PLATFORMS="pc emu efi-64"
PYTHON_SINGLE_TARGET="python3_14"
PYTHON_TARGETS="python3_14"
PYTHON_ABIS="3.14"
USE_PYTHON="3.14"
POSTGRES_TARGETS="postgres18"
CUDAARCHS="120"
PORTAGE_NICENESS="19"
MAKEOPTS="-j8 -l16"
EMERGE_DEFAULT_OPTS="--getbinpkg --binpkg-respect-use=y --binpkg-changed-deps=y --jobs 8 --load-average 16 --quiet-build=y --autounmask=y --autounmask-write --keep-going --verbose-conflicts --autounmask-backtrack=y --backtrack=100"
FEATURES="${FEATURES} getbinpkg binpkg-request-signature sandbox parallel-fetch metadata-transfer fail-clean -compressdebug"
CPU_FLAGS_X86="${CPU_FLAGS_X86} mmxext sse sse2 sse3 ssse3 avx avx2 f16c sse4_1 sse4_2"

USE="systemd -elogind -firmware"
# Boot & Firmware
#USE="${USE} uefi grub experimental aio"
# Compiler & Build Optimizations & Libraries & Frameworks & Desktop & UI
#USE="${USE} llvm_slot_21 -llvm_slot_19 -llvm_slot_20 lto pgo jit graphite gold lm_sensors openmp smp fortran glib boost icu introspection gstreamer dbus libnotify gd xml -gnome-keyring -nautilus gpm wayland tslib"
# Graphics GPU & Display & Image Formats & Processing
#USE="${USE} X wayland plasma nvidia uvm -cuda gpu g3dvl xa opengl egl vulkan vdpau vaapi gbm glamor osmesa openvg cairo sdl gtk gtk3 -gtk2 -kde -gnome qt6 -qt4 -qt5 xorg xrandr xcb drm kms libkms dmx xnest xvfb kdrive xv xvmc xinerama shaders layers vkd3d d3d9 uxa sna jpeg jpeg2k png tiff gif svg pdf exif lcms gimp gegl imagemagick devil qrcode"
# Languages & Development Tools & Vim & Security & Network
#USE="${USE} python java javafx lua script perl vala v8 tcl tk c++11 c++14 debugger profiler llcm-gcc vim-pager vim-syntax ssl sslv3 cryptsetup fido2 gpg pkcs11 hardened secure-delete hpn ipv6 wifi network ldap ovs avahi nsplugin vnc -automount -nss gnutls savedconfig acl gcrypt"
# Audio & Video & Codecs & Storage & Compression
#USE="${USE} alsa pulseaudio jack oss openal a52 aac faac faad flac mp3 ogg vorbis dts ffmpeg ffmpeg-mt -libav mpeg mpg123 x264 xvid divx dirac schroedinger theora bluray v4l v4l2 win32codecs coreavc wmf mng stereoscopic 3dnow 3dnowext lzma xz lz4 lzo zstd zip dvd cdr ieee1394 musicbrainz fdk vlc -mediacenter video"
# Fonts & Typography
#USE="${USE} truetype lcdfilter freetype -infinality -cleartype xetex kpathsea latex fontforge ms"
# Filesystems & Hardware & Kernel & D-Bus & System Services & Databases
#USE="${USE} ntfs vfat fat btrfs xfs jfs reiserfs reiser4 hfs f2fs aufs overlay xattr lvm dmraid mdadm udev acpi usb bluetooth kvm fuse threads kernel-patch -pax_kernel device-mapper pcap dbus udev -consolekit -policykit -hal sqlite postgres -mysql json"
# Math & Science & Misc & Extras
#USE="${USE} lapack flexiblas -mpi -mpi-threads R extras tools utils contrib extra dot postproc unicode cups djvu bash-completion gnuplot mercurial googledrive"
# Disabled / Negative flags
#USE="${USE} -bindist -doc -systemtap -eselect-ldso -kde -gnome -webkit -opencl -objc -objc++ -objc-gc -static-libs -pic -valgrind -apache -apache2 -qt4 -qt5 -mysql -hal -policykit -consolekit -automount -mpi -mpi-threads -hardened"

VIDEO_CARDS="intel radeon nouveau i810 i915 i965 r100 r200 r300 r600 radeonsi amdgpu radeon"
PORT_LOGDIR="/var/log/portage"
QEMU_SOFTMMU_TARGETS="arm x86_64"
QEMU_USER_TARGETS="arm armeb x86_64"
JAVA_HOME="/etc/java-config-2/current-system-vm"
GENTOO_MIRRORS="https://mirror.meowsmp.net/gentoo/ \
    https://[2a06:98c1:3120::b]/gentoo/ \
    https://188.114.97.11/gentoo/ \
    https://188.114.96.11/gentoo/ \
    https://104.21.48.24/gentoo/ \
    https://gentoo.kurdy.org/ \
    http://tux.rainside.sk/gentoo/ \
    https://gentoo.wcgw.art/ \
    https://138.201.51.8/ \
    https://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/"
